# Generated by Django 3.0.3 on 2021-10-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='movie_like',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
