# Generated by Django 3.0.3 on 2021-10-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraj', '0002_movielist_movie_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='movie_home',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
